export const page = {
  meta: {
    title: 'Agenda — FoodTuk Skewers',
    description: 'Waar je onze foodtruck de komende tijd kunt vinden. Bekijk onze agenda voor festivals, markten en events.',
  },
  heading: 'Komende events',
  subhead: 'Waar je onze foodtruck de komende tijd kunt vinden',
  emptyState: 'Geen events gepland op dit moment — maar we komen graag bij jou langs.',
  emptyCtaLabel: 'Vraag een offerte aan →',
  events: [
    {
      id: '1',
      dateIso: '2026-05-09',
      dayName: 'za',
      day: '9',
      month: 'mei',
      name: 'Rollende Keukens Amsterdam',
      location: 'Westergasfabriek, Amsterdam',
      time: '12:00 – 22:00',
      url: 'https://www.rollensdekeukens.nl',
      urlLabel: 'Meer info',
    },
    {
      id: '2',
      dateIso: '2026-05-23',
      dayName: 'za',
      day: '23',
      month: 'mei',
      name: 'Bruisend Breda Foodfestival',
      location: 'Chasséveld, Breda',
      time: '11:00 – 20:00',
      url: '',
      urlLabel: '',
    },
    {
      id: '3',
      dateIso: '2026-06-07',
      dayName: 'zo',
      day: '7',
      month: 'jun',
      name: 'Haagse Markt Zomerspecial',
      location: 'Herman Costerstraat, Den Haag',
      time: '09:00 – 17:00',
      url: '',
      urlLabel: '',
    },
    {
      id: '4',
      dateIso: '2026-06-20',
      dayName: 'za',
      day: '20',
      month: 'jun',
      name: 'De Parade Rotterdam',
      location: 'Museumpark, Rotterdam',
      time: '16:00 – 23:00',
      url: 'https://www.deparade.nl',
      urlLabel: 'Meer info',
    },
    {
      id: '5',
      dateIso: '2026-07-04',
      dayName: 'za',
      day: '4',
      month: 'jul',
      name: 'Zomermarkt Eindhoven',
      location: 'Stationsplein, Eindhoven',
      time: '10:00 – 19:00',
      url: '',
      urlLabel: '',
    },
  ],
  bottomCta: {
    heading: 'Staan we niet in jouw stad?',
    body: 'Vraag vrijblijvend een offerte aan en we komen graag naar jou toe.',
    label: 'Vraag een offerte aan →',
    href: '/#offerte-contact',
  },
} as const;
