export const page = {
  meta: {
    title: 'Agenda — FoodTuk Skewers',
    description: 'Waar je onze foodtruck de komende tijd kunt vinden. Bekijk onze agenda voor festivals, markten en events.',
  },
  heading: 'Komende events',
  subhead: 'Hier vind je ons op festivals en markten door heel Nederland. Staat je stad er niet bij? We komen ook naar jouw privé event.',
  emptyState: 'Geen events gepland op dit moment — maar we komen graag bij jou langs.',
  emptyCtaLabel: 'Vraag een offerte aan →',
  events: [
    { id: '1',  dateIso: '2026-05-09', dayName: 'za', day: '9',  month: 'mei', name: 'Rollende Keukens Amsterdam',      location: 'Westergasfabriek, Amsterdam',       time: '12:00 – 22:00', url: 'https://www.rollensdekeukens.nl', urlLabel: 'Meer info' },
    { id: '2',  dateIso: '2026-05-16', dayName: 'za', day: '16', month: 'mei', name: 'Foodtruckfestival Utrecht',        location: 'Griftpark, Utrecht',                time: '11:00 – 21:00', url: '', urlLabel: '' },
    { id: '3',  dateIso: '2026-05-23', dayName: 'za', day: '23', month: 'mei', name: 'Bruisend Breda Foodfestival',      location: 'Chasséveld, Breda',                 time: '11:00 – 20:00', url: '', urlLabel: '' },
    { id: '4',  dateIso: '2026-05-24', dayName: 'zo', day: '24', month: 'mei', name: 'Buurtmarkt Oud-West',              location: 'Jan Evertsenstraat, Amsterdam',     time: '10:00 – 17:00', url: '', urlLabel: '' },
    { id: '5',  dateIso: '2026-05-30', dayName: 'za', day: '30', month: 'mei', name: 'Streetfood Weekend Groningen',     location: 'Grote Markt, Groningen',            time: '12:00 – 22:00', url: 'https://streetfoodgroningen.nl', urlLabel: 'Meer info' },
    { id: '6',  dateIso: '2026-06-06', dayName: 'za', day: '6',  month: 'jun', name: 'Pinkstermarkt Haarlem',            location: 'Grote Markt, Haarlem',              time: '10:00 – 18:00', url: '', urlLabel: '' },
    { id: '7',  dateIso: '2026-06-07', dayName: 'zo', day: '7',  month: 'jun', name: 'Haagse Markt Zomerspecial',        location: 'Herman Costerstraat, Den Haag',     time: '09:00 – 17:00', url: '', urlLabel: '' },
    { id: '8',  dateIso: '2026-06-13', dayName: 'za', day: '13', month: 'jun', name: 'Bedrijfspicknick Philips',         location: 'High Tech Campus, Eindhoven',       time: '12:00 – 16:00', url: '', urlLabel: '' },
    { id: '9',  dateIso: '2026-06-20', dayName: 'za', day: '20', month: 'jun', name: 'De Parade Rotterdam',              location: 'Museumpark, Rotterdam',             time: '16:00 – 23:00', url: 'https://www.deparade.nl', urlLabel: 'Meer info' },
    { id: '10', dateIso: '2026-06-27', dayName: 'za', day: '27', month: 'jun', name: 'Zomerfestival Nijmegen',           location: 'Valkhof, Nijmegen',                 time: '14:00 – 22:00', url: '', urlLabel: '' },
    { id: '11', dateIso: '2026-07-04', dayName: 'za', day: '4',  month: 'jul', name: 'Zomermarkt Eindhoven',             location: 'Stationsplein, Eindhoven',          time: '10:00 – 19:00', url: '', urlLabel: '' },
    { id: '12', dateIso: '2026-07-11', dayName: 'za', day: '11', month: 'jul', name: 'Wereldkeuken Festival Tilburg',    location: 'Piusplein, Tilburg',                time: '12:00 – 22:00', url: 'https://wereldkeukentilburg.nl', urlLabel: 'Meer info' },
    { id: '13', dateIso: '2026-07-18', dayName: 'za', day: '18', month: 'jul', name: 'Sail Amsterdam Foodmarkt',         location: 'NDSM-werf, Amsterdam',             time: '10:00 – 23:00', url: '', urlLabel: '' },
    { id: '14', dateIso: '2026-08-01', dayName: 'za', day: '1',  month: 'aug', name: 'Zomercarnaval Rotterdam',          location: 'Coolsingel, Rotterdam',             time: '14:00 – 01:00', url: '', urlLabel: '' },
    { id: '15', dateIso: '2026-08-15', dayName: 'za', day: '15', month: 'aug', name: 'Lowlands Catering Partner',        location: 'Walibi, Biddinghuizen',            time: '12:00 – 00:00', url: 'https://lowlands.nl', urlLabel: 'Meer info' },
    { id: '16', dateIso: '2026-08-29', dayName: 'za', day: '29', month: 'aug', name: 'Uitmarkt Amsterdam',               location: 'Museumplein, Amsterdam',           time: '12:00 – 20:00', url: '', urlLabel: '' },
    { id: '17', dateIso: '2026-09-05', dayName: 'za', day: '5',  month: 'sep', name: 'Proef! Utrecht',                   location: 'Stadhuisplein, Utrecht',            time: '11:00 – 21:00', url: 'https://proefutrecht.nl', urlLabel: 'Meer info' },
    { id: '18', dateIso: '2026-09-19', dayName: 'za', day: '19', month: 'sep', name: 'Foodhallen Outdoor Market',        location: 'Foodhallen, Amsterdam',            time: '12:00 – 21:00', url: '', urlLabel: '' },
  ],
  bottomCta: {
    heading: 'Wij komen ook naar jouw privé event',
    body: 'Staat je stad er niet bij — of wil je ons inschakelen voor een bedrijfsfeest, trouwerij of festival? Vraag vrijblijvend een offerte aan.',
    label: 'Vraag een offerte aan →',
    href: '/#offerte-contact',
  },
} as const;
